name: reviewdog
on:
  - pull_request
jobs:
  eslint:
    name: runner / eslint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: eslint
        uses: reviewdog/action-eslint@v1
        with:
          reporter: github-pr-check # Change reporter.
          eslint_flags: 'src/**/*.{ts,tsx}'
          fail_on_error: true
