name: reviewdog
on:
  - pull_request
jobs:
  eslint:
    name: runner / eslint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'
      - run: yarn --frozen-lockfile
      - name: build
        run: yarn build
      - name: eslint
        uses: reviewdog/action-eslint@v1
        with:
          reporter: github-pr-check # Change reporter.
          eslint_flags: 'src/**/*.{ts,tsx}'
          fail_on_error: true
